on:
  workflow_dispatch
env:
  WF_VAR: "workflow variable"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
      - id: someStepId2
        run: echo this is a step with an id and run command
      - run: |
          pwd
          ls
      - run: |
          echo ${{ github.actor }}
          echo ${{ strategy.fail-fast }}
      - run: echo ${{ github.actor }}
      - run: echo ${{ strategy.fail-fast }}
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - run: echo "${{ toJson(runner) }}"
      - run: echo "${{ toJson(job) }}"
      - run: echo "${{ toJson(steps) }}"
        
        

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy
      - run: echo "ok not"
      - run: echo $WF_VAR
      - run: echo ${{ env.WF_VAR }}
      - run: echo another step
      - shell: python
        run: |
          x = 4
          print (x/2)
