on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy
      - run: echo "ok not"
      - run: echo another step
