on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
      - id: someStepId2
        run: echo this is a step with an id and run command
      - run: |
          pwd
          ls

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy
      - run: echo "ok not"
      - run: echo another step
      - shell: python
        run: |
          x = 4
          print (x/2)
