on:
  workflow_dispatch 
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
      - id: dockerContTest
        name: someName
        uses: docker://hello-world
      - uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'someone'
