name: containerTest

on:
  workflow_dispatch 
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3.0.0
        with:
          username: rockadeus
          password: ${{ SECRETS.DOCKER_HUB }}
      #- uses: docker/build-push-action@v5.0.0
        #with:
      - run: echo "test"
      - id: dockerContTest
        name: someName
        #uses: docker://hello-world
        uses: docker://rockadeus/docker101tutorial:latest
        #with:
          #args: someTestValue
      - uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'someone'
